# Constitutional Analysis Options
# Enforces architectural principles and best practices
# Last Updated: 2025-10-22

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"

  errors:
    # Enforce immutability
    prefer_const_constructors: error
    prefer_const_declarations: error
    prefer_const_literals_to_create_immutables: error

    # Prevent common mistakes
    avoid_print: error
    avoid_relative_lib_imports: error
    always_use_package_imports: error

    # Enforce null safety
    unnecessary_null_checks: error
    unnecessary_nullable_for_final_variable_declarations: error

linter:
  rules:
    # Style
    - prefer_single_quotes
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - prefer_final_fields
    - prefer_final_locals
    - prefer_final_in_for_each

    # Documentation
    - public_member_api_docs  # Enforce documentation

    # Code quality
    - avoid_empty_else
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_returning_null_for_future
    - avoid_slow_async_io
    - avoid_types_as_parameter_names
    - cancel_subscriptions
    - close_sinks
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - unnecessary_new
    - unnecessary_this

    # Architecture enforcement
    - always_use_package_imports  # No relative imports
    - avoid_web_libraries_in_flutter  # Platform-specific
    - implementation_imports  # Don't import src/
    - package_api_docs  # Document public APIs

    # Riverpod specific
    - avoid_manual_providers_as_generated_provider_dependency  # Use code gen

    # JSON serialization enforcement
    # (Will catch manual JSON parsing in code review)
