# ============================================================================
# MULTI-STAGE DOCKERFILE - 2025 BEST PRACTICE (SSOT COMPLIANT)
# ============================================================================
# IMPORTANT: API client generation happens via backend pre-commit hook
# Docker ONLY copies pre-generated files to ensure CI matches local builds
# ============================================================================
# Stage 1: Build Flutter Web App
# Stage 2: Production Image (nginx)
# ============================================================================

# ----------------------------------------------------------------------------
# STAGE 1: FLUTTER BUILD
# ----------------------------------------------------------------------------
FROM ghcr.io/cirruslabs/flutter:3.35.6 AS builder

WORKDIR /app

# Copy ENTIRE app including pre-generated API package
# CRITICAL: packages/frontend_easy_api is generated by backend pre-commit hook
# This ensures CI tests the EXACT same code that developer tested locally
COPY . .

# Install dependencies
RUN flutter pub get

# Install generated API package dependencies
WORKDIR /app/packages/frontend_easy_api
RUN flutter pub get

# Back to app root
WORKDIR /app

# Build optimized web app
# NOTE: Constitutional enforcement runs in backend pre-commit hook
RUN flutter build web --release

# ----------------------------------------------------------------------------
# STAGE 2: PRODUCTION (Nginx)
# ----------------------------------------------------------------------------
FROM nginx:alpine AS production

# Remove default nginx content
RUN rm -rf /usr/share/nginx/html/*

# Copy built Flutter web app
COPY --from=builder /app/build/web /usr/share/nginx/html

# Copy custom nginx config (optional)
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD wget --quiet --tries=1 --spider http://localhost/ || exit 1

# Run nginx
CMD ["nginx", "-g", "daemon off;"]
