# ============================================================================
# MULTI-STAGE DOCKERFILE - 2025 BEST PRACTICE (SSOT COMPLIANT)
# ============================================================================
# IMPORTANT: API client generation happens via backend pre-commit hook
# Docker ONLY copies pre-generated files to ensure CI matches local builds
# ============================================================================
# Stage 1: Build Flutter Web App
# Stage 2: Production Image (nginx)
# ============================================================================

# ----------------------------------------------------------------------------
# STAGE 1: FLUTTER BUILD
# ----------------------------------------------------------------------------
FROM ghcr.io/cirruslabs/flutter:3.35.6 AS builder

WORKDIR /app

# OPTIMIZATION: Copy dependency files first for better layer caching
# pubspec.yaml changes rarely, so this layer will be cached most of the time
COPY pubspec.yaml pubspec.lock ./
COPY packages/frontend_easy_api/pubspec.yaml packages/frontend_easy_api/
# Note: pubspec.lock for API package not in git, will be generated by flutter pub get

# Install dependencies (this layer is cached unless pubspec changes)
RUN flutter pub get

# Install generated API package dependencies
WORKDIR /app/packages/frontend_easy_api
RUN flutter pub get

# Back to app root
WORKDIR /app

# Copy the rest of the application code
# This invalidates cache only when source code changes
COPY . .

# Build arguments for production configuration (injected by CI)
ARG API_BASE_URL=https://easypool.in
ARG GOOGLE_MAPS_API_KEY

# Build optimized web app with production security hardening
# NOTE: Constitutional enforcement runs in backend pre-commit hook
# Security flags:
#   --release: Minifies & optimizes code
#   --no-source-maps: Prevents reverse engineering
#   --tree-shake-icons: Removes unused icons (smaller bundle)
#   --pwa-strategy: Enables offline PWA capabilities
RUN flutter build web --release \
    --dart-define=API_BASE_URL=${API_BASE_URL} \
    --no-source-maps \
    --tree-shake-icons \
    --pwa-strategy=offline-first

# Replace template placeholders in index.html with actual values
# This allows keeping secrets out of git while injecting at build time
RUN sed -i "s|{{GOOGLE_MAPS_API_KEY}}|${GOOGLE_MAPS_API_KEY}|g" /app/build/web/index.html

# ----------------------------------------------------------------------------
# STAGE 2: PRODUCTION (Nginx)
# ----------------------------------------------------------------------------
FROM nginx:alpine AS production

# Fix CVE-2025-58050: Update pcre2 to patched version
RUN apk upgrade --no-cache pcre2

# Remove default nginx content
RUN rm -rf /usr/share/nginx/html/*

# Copy built Flutter web app
COPY --from=builder /app/build/web /usr/share/nginx/html

# Copy custom nginx config (optional)
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD wget --quiet --tries=1 --spider http://localhost/ || exit 1

# Run nginx
CMD ["nginx", "-g", "daemon off;"]
