/// Google Product Standard - Example Custom Model
///
/// This demonstrates the correct use of freezed + json_serializable
/// for custom domain models (NOT API models - those are auto-generated).
///
/// Pattern:
/// - @freezed for immutability, copyWith, value equality
/// - @JsonSerializable via freezed integration for JSON conversion
/// - Use for: app state, user preferences, custom business logic models
///
/// IMPORTANT: Freezed 3.x requires 'sealed' or 'abstract' keyword

import 'package:freezed_annotation/freezed_annotation.dart';

part 'app_state.freezed.dart';
part 'app_state.g.dart';

/// Application state model - Google Product Standard 2025
/// Uses 'sealed' for simple data models with single constructor
@freezed
sealed class AppState with _$AppState {
  const factory AppState({
    required String userId,
    required bool isOnline,
    @Default(false) bool isDarkMode,
    @Default(0) int unreadNotifications,
  }) = _AppState;

  /// JSON deserialization - auto-generated by freezed + json_serializable
  factory AppState.fromJson(Map<String, dynamic> json) =>
      _$AppStateFromJson(json);
}
